#============== Global Options ================
MKFILE_DIR := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))
LLVM_DIR ?= $(abspath $(MKFILE_DIR)/../llvm-project/build/bin)
TYP_DIR ?= $(abspath $(MKFILE_DIR)/../../)

LINKEDBIN := build/_main_._all_._files_._linked_.bc

CC := ${LLVM_DIR}/clang -std=gnu89 -B /usr/bin -DSPEC -DNDEBUG
CXX := ${LLVM_DIR}/clang++ -std=gnu++98 -B /usr/bin -DSPEC -DNDEBUG
LLOPT := ${LLVM_DIR}/opt
LLD := ${LLVM_DIR}/ld.lld
LLDIS := ${LLVM_DIR}/llvm-dis
LLINK := ${LLVM_DIR}/llvm-link
OBJDUMP := ${LLVM_DIR}/llvm-objdump
BLD := ${CXX}

mkfile_path := $(abspath $(lastword $(MAKEFILE_LIST)))
current_dir := $(patsubst %/,%,$(dir $(mkfile_path)))

OPTTIMECMD := ${current_dir}/../time/time -f "OPT Total Time: %e"
LLCTIMECMD := ${current_dir}/../time/time -f "LLC Total Time: %e"
LLDTIMECMD := ${current_dir}/../time/time -f "LLD Total Time: %e"

OPT := -Os -fno-vectorize -fno-slp-vectorize -fno-unroll-loops -fno-inline-functions -fPIC

LBINS = $(addsuffix .bc,$(basename $(SRC)))

#================ Default FM Options ======================
#Can be overriden
TECHNIQUE ?= baseline
ALIGNMENT ?= nw
DEBUG ?= false
VERBOSE ?= false

FROM_SCRATCH ?= true
TIMING ?= false
DISASSEMBLE ?= false

F3M_ADAPT_THR ?= false
F3M_ADAPT_BANDS ?= false
F3M_ROWS ?= 2
F3M_BANDS ?= 100
MH_ACROSS ?= true
F3M_RANKDIST ?= 1.0
BUCKET_SIZE_CAP ?= 100
REPORT ?= false
MATCHER_REPORT ?= false
OP_REORDER ?= false
WHOLE_PROGRAM ?= true
PAIRS_FILE ?= 
NAME = $(TECHNIQUE)
# ============ Added Code ===============
PREDICTALIGNMENT = false
# =======================================


ifeq ($(WHOLE_PROGRAM), true)
	BASELINE_FLAGS := -passes='internalize,globaldce,mergefunc' -internalize-public-api-list=main
else
	BASELINE_FLAGS ?= -passes='mergefunc'
endif

#======== Non-SALSSA Flags Generation ========
ifeq ($(TECHNIQUE), baseline)
ifeq ($(WHOLE_PROGRAM), true)
	FM_FLAGS ?= -passes='internalize,globaldce' -internalize-public-api-list=main
else
	FM_FLAGS ?=
endif
endif

ifeq ($(TECHNIQUE), llvm)
ifeq ($(WHOLE_PROGRAM), true)
	FM_FLAGS ?= -passes='internalize,globaldce,mergefunc' -internalize-public-api-list=main
else
	FM_FLAGS ?= -passes='mergefunc'
endif
endif

#========== SALSSA Flags Generation ==========
# Removed because they are default in the pass:
#-func-merging-reuse-merges=true 
#-func-merging-threshold=0 
#-func-merging-ranking-threshold=0
#-func-merging-explore=1
#-func-merging-max-param=true
#-func-merging-identic-type=true
#-func-merging-unify-return=false


ifeq ($(WHOLE_PROGRAM), true)
	SALSSA_FLAGS := -passes='internalize,globaldce,mergefunc,func-merging' -internalize-public-api-list=main -func-merging-operand-reorder=$(OP_REORDER) -func-merging-coalescing=false -func-merging-whole-program=$(WHOLE_PROGRAM) -func-merging-matcher-report=$(MATCHER_REPORT) -func-merging-debug=$(DEBUG) -func-merging-verbose=$(VERBOSE) $(OTHER_FLAGS)
else
	SALSSA_FLAGS := -passes='mergefunc,func-merging' -func-merging-operand-reorder=$(OP_REORDER) -func-merging-coalescing=false -func-merging-whole-program=$(WHOLE_PROGRAM) -func-merging-matcher-report=$(MATCHER_REPORT) -func-merging-debug=$(DEBUG) -func-merging-verbose=$(VERBOSE) $(OTHER_FLAGS)
endif

ifeq ($(TECHNIQUE), salssa)
	FM_FLAGS ?= $(SALSSA_FLAGS)
endif

ifeq ($(TECHNIQUE), hyfm)
	FM_FLAGS ?= $(SALSSA_FLAGS) -hyfm-profitability=true
	hyfm_based = yes
endif

ifeq ($(TECHNIQUE), f3m)
	FM_FLAGS ?= $(SALSSA_FLAGS) -hyfm-profitability=true -func-merging-f3m=true -adaptive-threshold=$(F3M_ADAPT_THR) -adaptive-bands=$(F3M_ADAPT_BANDS) -hyfm-f3m-rows=$(F3M_ROWS) -hyfm-f3m-bands=$(F3M_BANDS) -shingling-cross-basic-blocks=$(MH_ACROSS) -ranking-distance=$(F3M_RANKDIST) -bucket-size-cap=$(BUCKET_SIZE_CAP) -func-merging-report=$(REPORT)
	hyfm_based = yes
endif

# ============ Added Code ===============
ifeq ($(TECHNIQUE), f3m-predict-dotprod)
	FM_FLAGS ?= $(SALSSA_FLAGS) -hyfm-profitability=true -func-merging-f3m=true -adaptive-threshold=$(F3M_ADAPT_THR) -adaptive-bands=$(F3M_ADAPT_BANDS) -hyfm-f3m-rows=$(F3M_ROWS) -hyfm-f3m-bands=$(F3M_BANDS) -shingling-cross-basic-blocks=$(MH_ACROSS) -ranking-distance=$(F3M_RANKDIST) -bucket-size-cap=$(BUCKET_SIZE_CAP) -func-merging-report=$(REPORT)
	FM_FLAGS += -predict-alignment -benchmark-name=$(BENCH) -typ-dir=$(TYP_DIR) -model-name="DotProdSiameseModel"
	hyfm_based = yes
endif
ifeq ($(TECHNIQUE), f3m-predict-attention)
	FM_FLAGS ?= $(SALSSA_FLAGS) -hyfm-profitability=true -func-merging-f3m=true -adaptive-threshold=$(F3M_ADAPT_THR) -adaptive-bands=$(F3M_ADAPT_BANDS) -hyfm-f3m-rows=$(F3M_ROWS) -hyfm-f3m-bands=$(F3M_BANDS) -shingling-cross-basic-blocks=$(MH_ACROSS) -ranking-distance=$(F3M_RANKDIST) -bucket-size-cap=$(BUCKET_SIZE_CAP) -func-merging-report=$(REPORT)
	FM_FLAGS += -predict-alignment -benchmark-name=$(BENCH) -typ-dir=$(TYP_DIR) -model-name="MultiHeadAttention"
	hyfm_based = yes
endif

FM_FLAGS += -func-merging-reuse-merges=false
#========================================

ifdef hyfm_based
ifeq ($(ALIGNMENT), pa)
	FM_FLAGS += -func-merging-hyfm-pa=true
	NAME := $(NAME)-pa
else
	FM_FLAGS += -func-merging-hyfm-nw=true
	NAME := $(NAME)-nw
endif

ifneq ($(PAIRS_FILE), )
	FM_FLAGS += -func-merging-pairs-file=$(PAIRS_FILE)
endif
endif

